Redirect call for proposal to another page if cfp is closed
djangocon/2017.djangocon.eu pull request #23
Opened 2016-12-30 17:20 UTC by EmadMokhtar

Redirect call for proposal to another page if cfp is closed.

2017-01-01 23:20 UTC, yakky requested changes

2017-01-01 23:20 UTC, yakky commented on djangocon_europe/settings.py
> +CFP_CLOSING_DATE = env('CFP_CLOSING_DATE')
A Default must be provided here. I actually don't think we need this from the environment. Can be easily hardcoded in settings

2017-01-01 23:20 UTC, yakky commented
@EmadMokhtar Thanks, it looks really nice. Only minor comment added

2017-01-02 08:50 UTC, EmadMokhtar commented on djangocon_europe/settings.py
> +CFP_CLOSING_DATE = env('CFP_CLOSING_DATE')
@yakky One question, Are users can submit on 8th of Jan. 2017?

2017-01-02 08:51 UTC, yakky commented on djangocon_europe/settings.py
> +CFP_CLOSING_DATE = env('CFP_CLOSING_DATE')
Yes. 2017-01-08 24.00 CET (or 2017-01-09 00.00 CET)

2017-01-02 08:52 UTC, EmadMokhtar commented on djangocon_europe/settings.py
> +CFP_CLOSING_DATE = env('CFP_CLOSING_DATE')
Perfect, Thanks 👍

2017-01-02 21:52 UTC, yakky approved these changes

2017-01-02 21:55 UTC, yakky commented
@EmadMokhtar nice, thanks for completing this!

2017-01-02 21:55 UTC, merged